"""Comprehensive NSE 500+ Universe covering Nifty 50, Next 50, Midcap 150, and Smallcap 250."""

NSE_UNIVERSE: list[dict] = [
    {'symbol': 'RELIANCE', 'name': 'Reliance Industries Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'TCS', 'name': 'Tata Consultancy Services Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'HDFCBANK', 'name': 'HDFC Bank Ltd.', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'ICICIBANK', 'name': 'ICICI Bank Ltd.', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'INFY', 'name': 'Infosys Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'HINDUNILVR', 'name': 'Hindustan Unilever Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'ITC', 'name': 'ITC Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'SBIN', 'name': 'State Bank of India', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'BHARTIARTL', 'name': 'Bharti Airtel Ltd.', 'sector': 'Telecom', 'cap': 'Largecap'},
    {'symbol': 'KOTAKBANK', 'name': 'Kotak Mahindra Bank Ltd.', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'LT', 'name': 'Larsen & Toubro Ltd.', 'sector': 'Capital Goods', 'cap': 'Largecap'},
    {'symbol': 'AXISBANK', 'name': 'Axis Bank Ltd.', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'BAJFINANCE', 'name': 'Bajaj Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'BAJAJFINSV', 'name': 'Bajaj Finserv Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'ASIANPAINT', 'name': 'Asian Paints Ltd.', 'sector': 'Consumer Durables', 'cap': 'Largecap'},
    {'symbol': 'MARUTI', 'name': 'Maruti Suzuki India Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'HCLTECH', 'name': 'HCL Technologies Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'TITAN', 'name': 'Titan Company Ltd.', 'sector': 'Consumer Durables', 'cap': 'Largecap'},
    {'symbol': 'SUNPHARMA', 'name': 'Sun Pharmaceutical Industries Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'TATAMOTORS', 'name': 'Tata Motors Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'NTPC', 'name': 'NTPC Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'ULTRACEMCO', 'name': 'UltraTech Cement Ltd.', 'sector': 'Cement', 'cap': 'Largecap'},
    {'symbol': 'POWERGRID', 'name': 'Power Grid Corporation of India Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'WIPRO', 'name': 'Wipro Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'NESTLEIND', 'name': 'Nestle India Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'TECHM', 'name': 'Tech Mahindra Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'JSWSTEEL', 'name': 'JSW Steel Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'TATASTEEL', 'name': 'Tata Steel Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'INDUSINDBK', 'name': 'IndusInd Bank Ltd.', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'M&M', 'name': 'Mahindra & Mahindra Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'ONGC', 'name': 'Oil and Natural Gas Corporation Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'COALINDIA', 'name': 'Coal India Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'ADANIENT', 'name': 'Adani Enterprises Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'ADANIPORTS', 'name': 'Adani Ports and Special Economic Zone Ltd.', 'sector': 'Infrastructure', 'cap': 'Largecap'},
    {'symbol': 'BPCL', 'name': 'Bharat Petroleum Corporation Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'GRASIM', 'name': 'Grasim Industries Ltd.', 'sector': 'Cement', 'cap': 'Largecap'},
    {'symbol': 'CIPLA', 'name': 'Cipla Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'DRREDDY', 'name': 'Dr. Reddy\'s Laboratories Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'APOLLOHOSP', 'name': 'Apollo Hospitals Enterprise Ltd.', 'sector': 'Healthcare', 'cap': 'Largecap'},
    {'symbol': 'EICHERMOT', 'name': 'Eicher Motors Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'HEROMOTOCO', 'name': 'Hero MotoCorp Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'DIVISLAB', 'name': 'Divi\'s Laboratories Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'TATACONSUM', 'name': 'Tata Consumer Products Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'BRITANNIA', 'name': 'Britannia Industries Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'BAJAJ-AUTO', 'name': 'Bajaj Auto Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'SBILIFE', 'name': 'SBI Life Insurance Company Ltd.', 'sector': 'Insurance', 'cap': 'Largecap'},
    {'symbol': 'HDFCLIFE', 'name': 'HDFC Life Insurance Company Ltd.', 'sector': 'Insurance', 'cap': 'Largecap'},
    {'symbol': 'HINDALCO', 'name': 'Hindalco Industries Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'UPL', 'name': 'UPL Ltd.', 'sector': 'Chemicals', 'cap': 'Largecap'},
    {'symbol': 'SHRIRAMFIN', 'name': 'Shriram Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'ADANIGREEN', 'name': 'Adani Green Energy Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'ADANIPOWER', 'name': 'Adani Power Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'ATGL', 'name': 'Adani Total Gas Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'AMBUJACEM', 'name': 'Ambuja Cements Ltd.', 'sector': 'Cement', 'cap': 'Largecap'},
    {'symbol': 'BANKBARODA', 'name': 'Bank of Baroda', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'BEL', 'name': 'Bharat Electronics Ltd.', 'sector': 'Defence', 'cap': 'Largecap'},
    {'symbol': 'BOSCHLTD', 'name': 'Bosch Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'CANBK', 'name': 'Canara Bank', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'CHOLAFIN', 'name': 'Cholamandalam Investment and Finance Co Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'DABUR', 'name': 'Dabur India Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'DLF', 'name': 'DLF Ltd.', 'sector': 'Real Estate', 'cap': 'Largecap'},
    {'symbol': 'GAIL', 'name': 'GAIL (India) Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'GODREJCP', 'name': 'Godrej Consumer Products Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'HAL', 'name': 'Hindustan Aeronautics Ltd.', 'sector': 'Defence', 'cap': 'Largecap'},
    {'symbol': 'HAVELLS', 'name': 'Havells India Ltd.', 'sector': 'Consumer Durables', 'cap': 'Largecap'},
    {'symbol': 'ICICIGI', 'name': 'ICICI Lombard General Insurance Co Ltd.', 'sector': 'Insurance', 'cap': 'Largecap'},
    {'symbol': 'ICICIPRULI', 'name': 'ICICI Prudential Life Insurance Co Ltd.', 'sector': 'Insurance', 'cap': 'Largecap'},
    {'symbol': 'IOC', 'name': 'Indian Oil Corporation Ltd.', 'sector': 'Oil & Gas', 'cap': 'Largecap'},
    {'symbol': 'IRCTC', 'name': 'Indian Railway Catering and Tourism Corp Ltd.', 'sector': 'Services', 'cap': 'Largecap'},
    {'symbol': 'IRFC', 'name': 'Indian Railway Finance Corporation Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'JINDALSTEL', 'name': 'Jindal Steel & Power Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'JIOFIN', 'name': 'Jio Financial Services Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'LTIM', 'name': 'LTIMindtree Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'MARICO', 'name': 'Marico Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'MOTHERSON', 'name': 'Samvardhana Motherson International Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'NAUKRI', 'name': 'Info Edge (India) Ltd.', 'sector': 'IT', 'cap': 'Largecap'},
    {'symbol': 'NHPC', 'name': 'NHPC Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'PIDILITIND', 'name': 'Pidilite Industries Ltd.', 'sector': 'Chemicals', 'cap': 'Largecap'},
    {'symbol': 'PFC', 'name': 'Power Finance Corporation Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'PNB', 'name': 'Punjab National Bank', 'sector': 'Banking', 'cap': 'Largecap'},
    {'symbol': 'RECLTD', 'name': 'REC Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'RVNL', 'name': 'Rail Vikas Nigam Ltd.', 'sector': 'Infrastructure', 'cap': 'Largecap'},
    {'symbol': 'SBICARD', 'name': 'SBI Cards and Payment Services Ltd.', 'sector': 'Financial Services', 'cap': 'Largecap'},
    {'symbol': 'SIEMENS', 'name': 'Siemens Ltd.', 'sector': 'Capital Goods', 'cap': 'Largecap'},
    {'symbol': 'SRF', 'name': 'SRF Ltd.', 'sector': 'Chemicals', 'cap': 'Largecap'},
    {'symbol': 'TATAPOWER', 'name': 'Tata Power Co Ltd.', 'sector': 'Power', 'cap': 'Largecap'},
    {'symbol': 'TORNTPHARM', 'name': 'Torrent Pharmaceuticals Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'TVSMOTOR', 'name': 'TVS Motor Company Ltd.', 'sector': 'Auto', 'cap': 'Largecap'},
    {'symbol': 'UNITDSPR', 'name': 'United Spirits Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'VBL', 'name': 'Varun Beverages Ltd.', 'sector': 'FMCG', 'cap': 'Largecap'},
    {'symbol': 'VEDL', 'name': 'Vedanta Ltd.', 'sector': 'Metals', 'cap': 'Largecap'},
    {'symbol': 'ZOMATO', 'name': 'Zomato Ltd.', 'sector': 'Services', 'cap': 'Largecap'},
    {'symbol': 'ZYDUSLIFE', 'name': 'Zydus Lifesciences Ltd.', 'sector': 'Pharma', 'cap': 'Largecap'},
    {'symbol': 'ASHOKLEY', 'name': 'Ashok Leyland Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'ASTRAL', 'name': 'Astral Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'AUBANK', 'name': 'AU Small Finance Bank Ltd.', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'BALKRISIND', 'name': 'Balkrishna Industries Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'BALRAMCHIN', 'name': 'Balrampur Chini Mills Ltd.', 'sector': 'Sugar', 'cap': 'Midcap'},
    {'symbol': 'BANDHANBNK', 'name': 'Bandhan Bank Ltd.', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'BATAINDIA', 'name': 'Bata India Ltd.', 'sector': 'Consumer Durables', 'cap': 'Midcap'},
    {'symbol': 'BERGEPAINT', 'name': 'Berger Paints India Ltd.', 'sector': 'Consumer Durables', 'cap': 'Midcap'},
    {'symbol': 'BHARATFORG', 'name': 'Bharat Forge Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'BHEL', 'name': 'Bharat Heavy Electricals Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'BIOCON', 'name': 'Biocon Ltd.', 'sector': 'Pharma', 'cap': 'Midcap'},
    {'symbol': 'COFORGE', 'name': 'Coforge Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'COLPAL', 'name': 'Colgate-Palmolive (India) Ltd.', 'sector': 'FMCG', 'cap': 'Midcap'},
    {'symbol': 'CONCOR', 'name': 'Container Corporation of India Ltd.', 'sector': 'Logistics', 'cap': 'Midcap'},
    {'symbol': 'COROMANDEL', 'name': 'Coromandel International Ltd.', 'sector': 'Chemicals', 'cap': 'Midcap'},
    {'symbol': 'CROMPTON', 'name': 'Crompton Greaves Consumer Electricals Ltd.', 'sector': 'Consumer Durables', 'cap': 'Midcap'},
    {'symbol': 'CUMMINSIND', 'name': 'Cummins India Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'DEEPAKNTR', 'name': 'Deepak Nitrite Ltd.', 'sector': 'Chemicals', 'cap': 'Midcap'},
    {'symbol': 'DELHIVERY', 'name': 'Delhivery Ltd.', 'sector': 'Logistics', 'cap': 'Midcap'},
    {'symbol': 'DIXON', 'name': 'Dixon Technologies (India) Ltd.', 'sector': 'Consumer Durables', 'cap': 'Midcap'},
    {'symbol': 'ESCORTS', 'name': 'Escorts Kubota Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'EXIDEIND', 'name': 'Exide Industries Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'FEDERALBNK', 'name': 'The Federal Bank Ltd.', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'FORTIS', 'name': 'Fortis Healthcare Ltd.', 'sector': 'Healthcare', 'cap': 'Midcap'},
    {'symbol': 'GLENMARK', 'name': 'Glenmark Pharmaceuticals Ltd.', 'sector': 'Pharma', 'cap': 'Midcap'},
    {'symbol': 'GMRINFRA', 'name': 'GMR Airports Infrastructure Ltd.', 'sector': 'Infrastructure', 'cap': 'Midcap'},
    {'symbol': 'GODREJPROP', 'name': 'Godrej Properties Ltd.', 'sector': 'Real Estate', 'cap': 'Midcap'},
    {'symbol': 'GUJGASLTD', 'name': 'Gujarat Gas Ltd.', 'sector': 'Oil & Gas', 'cap': 'Midcap'},
    {'symbol': 'HDFCAMC', 'name': 'HDFC Asset Management Company Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'HINDPETRO', 'name': 'Hindustan Petroleum Corporation Ltd.', 'sector': 'Oil & Gas', 'cap': 'Midcap'},
    {'symbol': 'IDFCFIRSTB', 'name': 'IDFC First Bank Ltd.', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'INDIANB', 'name': 'Indian Bank', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'INDHOTEL', 'name': 'The Indian Hotels Co Ltd.', 'sector': 'Services', 'cap': 'Midcap'},
    {'symbol': 'IPCALAB', 'name': 'IPCA Laboratories Ltd.', 'sector': 'Pharma', 'cap': 'Midcap'},
    {'symbol': 'JSL', 'name': 'Jindal Stainless Ltd.', 'sector': 'Metals', 'cap': 'Midcap'},
    {'symbol': 'JUBLFOOD', 'name': 'Jubilant FoodWorks Ltd.', 'sector': 'Services', 'cap': 'Midcap'},
    {'symbol': 'KPITTECH', 'name': 'KPIT Technologies Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'L&TFH', 'name': 'L&T Finance Holdings Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'LALPATHLAB', 'name': 'Dr. Lal PathLabs Ltd.', 'sector': 'Healthcare', 'cap': 'Midcap'},
    {'symbol': 'LAURUSLABS', 'name': 'Laurus Labs Ltd.', 'sector': 'Pharma', 'cap': 'Midcap'},
    {'symbol': 'LICHSGFIN', 'name': 'LIC Housing Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'LUPIN', 'name': 'Lupin Ltd.', 'sector': 'Pharma', 'cap': 'Midcap'},
    {'symbol': 'MAXHEALTH', 'name': 'Max Healthcare Institute Ltd.', 'sector': 'Healthcare', 'cap': 'Midcap'},
    {'symbol': 'MFSL', 'name': 'Max Financial Services Ltd.', 'sector': 'Insurance', 'cap': 'Midcap'},
    {'symbol': 'MPHASIS', 'name': 'Mphasis Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'MRF', 'name': 'MRF Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'MUTHOOTFIN', 'name': 'Muthoot Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'NATIONALUM', 'name': 'National Aluminium Co Ltd.', 'sector': 'Metals', 'cap': 'Midcap'},
    {'symbol': 'NMDC', 'name': 'NMDC Ltd.', 'sector': 'Metals', 'cap': 'Midcap'},
    {'symbol': 'OBEROIRLTY', 'name': 'Oberoi Realty Ltd.', 'sector': 'Real Estate', 'cap': 'Midcap'},
    {'symbol': 'OFSS', 'name': 'Oracle Financial Services Software Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'PAGEIND', 'name': 'Page Industries Ltd.', 'sector': 'Textiles', 'cap': 'Midcap'},
    {'symbol': 'PERSISTENT', 'name': 'Persistent Systems Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'PETRONET', 'name': 'Petronet LNG Ltd.', 'sector': 'Oil & Gas', 'cap': 'Midcap'},
    {'symbol': 'PHOENIXLTD', 'name': 'The Phoenix Mills Ltd.', 'sector': 'Real Estate', 'cap': 'Midcap'},
    {'symbol': 'POLYCAB', 'name': 'Polycab India Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'POONAWALLA', 'name': 'Poonawalla Fincorp Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'PRESTIGE', 'name': 'Prestige Estates Projects Ltd.', 'sector': 'Real Estate', 'cap': 'Midcap'},
    {'symbol': 'SAIL', 'name': 'Steel Authority of India Ltd.', 'sector': 'Metals', 'cap': 'Midcap'},
    {'symbol': 'SBIMF', 'name': 'SBI Funds Management Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'SCHAEFFLER', 'name': 'Schaeffler India Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'SOLARINDS', 'name': 'Solar Industries India Ltd.', 'sector': 'Chemicals', 'cap': 'Midcap'},
    {'symbol': 'SONACOMS', 'name': 'Sona BLW Precision Forgings Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'SUNDARMFIN', 'name': 'Sundaram Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Midcap'},
    {'symbol': 'SUNDRMFAST', 'name': 'Sundram Fasteners Ltd.', 'sector': 'Auto', 'cap': 'Midcap'},
    {'symbol': 'SUNTV', 'name': 'Sun TV Network Ltd.', 'sector': 'Media', 'cap': 'Midcap'},
    {'symbol': 'SUPREMEIND', 'name': 'Supreme Industries Ltd.', 'sector': 'Capital Goods', 'cap': 'Midcap'},
    {'symbol': 'SUZLON', 'name': 'Suzlon Energy Ltd.', 'sector': 'Power', 'cap': 'Midcap'},
    {'symbol': 'SYNGENE', 'name': 'Syngene International Ltd.', 'sector': 'Healthcare', 'cap': 'Midcap'},
    {'symbol': 'TATACHEM', 'name': 'Tata Chemicals Ltd.', 'sector': 'Chemicals', 'cap': 'Midcap'},
    {'symbol': 'TATACOMM', 'name': 'Tata Communications Ltd.', 'sector': 'Telecom', 'cap': 'Midcap'},
    {'symbol': 'TATAELXSI', 'name': 'Tata Elxsi Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'TATATECH', 'name': 'Tata Technologies Ltd.', 'sector': 'IT', 'cap': 'Midcap'},
    {'symbol': 'TORNTPOWER', 'name': 'Torrent Power Ltd.', 'sector': 'Power', 'cap': 'Midcap'},
    {'symbol': 'TRENT', 'name': 'Trent Ltd.', 'sector': 'Services', 'cap': 'Midcap'},
    {'symbol': 'UNIONBANK', 'name': 'Union Bank of India', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'VOLTAS', 'name': 'Voltas Ltd.', 'sector': 'Consumer Durables', 'cap': 'Midcap'},
    {'symbol': 'YESBANK', 'name': 'Yes Bank Ltd.', 'sector': 'Banking', 'cap': 'Midcap'},
    {'symbol': 'ZEEL', 'name': 'Zee Entertainment Enterprises Ltd.', 'sector': 'Media', 'cap': 'Midcap'},
    {'symbol': 'AWL', 'name': 'AWL Agri Business Ltd.', 'sector': 'FMCG', 'cap': 'Smallcap'},
    {'symbol': 'ANGELONE', 'name': 'Angel One Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'APLAPOLLO', 'name': 'APL Apollo Tubes Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'ASTERDM', 'name': 'Aster DM Healthcare Ltd.', 'sector': 'Healthcare', 'cap': 'Smallcap'},
    {'symbol': 'AVANTIFEED', 'name': 'Avanti Feeds Ltd.', 'sector': 'FMCG', 'cap': 'Smallcap'},
    {'symbol': 'BECTORFOOD', 'name': 'Mrs. Bectors Food Specialities Ltd.', 'sector': 'FMCG', 'cap': 'Smallcap'},
    {'symbol': 'BBL', 'name': 'Bharat Bijlee Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'BLS', 'name': 'BLS International Services Ltd.', 'sector': 'Services', 'cap': 'Smallcap'},
    {'symbol': 'BORORENEW', 'name': 'Borosil Renewables Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'BRIGADE', 'name': 'Brigade Enterprises Ltd.', 'sector': 'Real Estate', 'cap': 'Smallcap'},
    {'symbol': 'BSOFT', 'name': 'Birlasoft Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'CAMPUS', 'name': 'Campus Activewear Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'CAMS', 'name': 'Computer Age Management Services Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'CASTROLIND', 'name': 'Castrol India Ltd.', 'sector': 'Oil & Gas', 'cap': 'Smallcap'},
    {'symbol': 'CDSL', 'name': 'Central Depository Services (India) Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'CENTURYPLY', 'name': 'Century Plyboards (India) Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'CERA', 'name': 'Cera Sanitaryware Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'CESC', 'name': 'CESC Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'CHAMBLFERT', 'name': 'Chambal Fertilisers and Chemicals Ltd.', 'sector': 'Chemicals', 'cap': 'Smallcap'},
    {'symbol': 'CLEAN', 'name': 'Clean Science and Technology Ltd.', 'sector': 'Chemicals', 'cap': 'Smallcap'},
    {'symbol': 'COCHINSHIP', 'name': 'Cochin Shipyard Ltd.', 'sector': 'Defence', 'cap': 'Smallcap'},
    {'symbol': 'CYIENT', 'name': 'Cyient Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'DATAPATTNS', 'name': 'Data Patterns (India) Ltd.', 'sector': 'Defence', 'cap': 'Smallcap'},
    {'symbol': 'EIDPARRY', 'name': 'E.I.D. - Parry (India) Ltd.', 'sector': 'Sugar', 'cap': 'Smallcap'},
    {'symbol': 'EQUITASBNK', 'name': 'Equitas Small Finance Bank Ltd.', 'sector': 'Banking', 'cap': 'Smallcap'},
    {'symbol': 'FSL', 'name': 'Firstsource Solutions Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'GLS', 'name': 'Glenmark Life Sciences Ltd.', 'sector': 'Pharma', 'cap': 'Smallcap'},
    {'symbol': 'GNFC', 'name': 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd.', 'sector': 'Chemicals', 'cap': 'Smallcap'},
    {'symbol': 'GPIL', 'name': 'Godawari Power and Ispat Ltd.', 'sector': 'Metals', 'cap': 'Smallcap'},
    {'symbol': 'GRANULES', 'name': 'Granules India Ltd.', 'sector': 'Pharma', 'cap': 'Smallcap'},
    {'symbol': 'GREENPOWER', 'name': 'Orient Green Power Company Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'GTLINFRA', 'name': 'GTL Infrastructure Ltd.', 'sector': 'Telecom', 'cap': 'Smallcap'},
    {'symbol': 'HAPPSTMNDS', 'name': 'Happiest Minds Technologies Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'HFCL', 'name': 'HFCL Ltd.', 'sector': 'Telecom', 'cap': 'Smallcap'},
    {'symbol': 'HGS', 'name': 'Hinduja Global Solutions Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'HUDCO', 'name': 'Housing & Urban Development Corporation Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'IDBI', 'name': 'IDBI Bank Ltd.', 'sector': 'Banking', 'cap': 'Smallcap'},
    {'symbol': 'IIFL', 'name': 'IIFL Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'INDIGOPNTS', 'name': 'Indigo Paints Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'INOXWIND', 'name': 'Inox Wind Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'IEX', 'name': 'Indian Energy Exchange Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'JBCHEPHARM', 'name': 'J.B. Chemicals & Pharmaceuticals Ltd.', 'sector': 'Pharma', 'cap': 'Smallcap'},
    {'symbol': 'JKCEMENT', 'name': 'JK Cement Ltd.', 'sector': 'Cement', 'cap': 'Smallcap'},
    {'symbol': 'JKPAPER', 'name': 'JK Paper Ltd.', 'sector': 'Paper', 'cap': 'Smallcap'},
    {'symbol': 'JPPOWER', 'name': 'Jaiprakash Power Ventures Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'KALYANKJIL', 'name': 'Kalyan Jewellers India Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'KARURVYSYA', 'name': 'The Karur Vysya Bank Ltd.', 'sector': 'Banking', 'cap': 'Smallcap'},
    {'symbol': 'KEC', 'name': 'KEC International Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'KFINTECH', 'name': 'KFin Technologies Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'LATENTVIEW', 'name': 'Latent View Analytics Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'MAHLIFE', 'name': 'Mahindra Lifespace Developers Ltd.', 'sector': 'Real Estate', 'cap': 'Smallcap'},
    {'symbol': 'MANAPPURAM', 'name': 'Manappuram Finance Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'MASTEK', 'name': 'Mastek Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'MAZDOCK', 'name': 'Mazagon Dock Shipbuilders Ltd.', 'sector': 'Defence', 'cap': 'Smallcap'},
    {'symbol': 'METROPOLIS', 'name': 'Metropolis Healthcare Ltd.', 'sector': 'Healthcare', 'cap': 'Smallcap'},
    {'symbol': 'NBCC', 'name': 'NBCC (India) Ltd.', 'sector': 'Infrastructure', 'cap': 'Smallcap'},
    {'symbol': 'NCC', 'name': 'NCC Ltd.', 'sector': 'Infrastructure', 'cap': 'Smallcap'},
    {'symbol': 'NETWORK18', 'name': 'Network18 Media & Investments Ltd.', 'sector': 'Media', 'cap': 'Smallcap'},
    {'symbol': 'NLCINDIA', 'name': 'NLC India Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'OLAELEC', 'name': 'Ola Electric Mobility Ltd.', 'sector': 'Auto', 'cap': 'Smallcap'},
    {'symbol': 'PATANJALI', 'name': 'Patanjali Foods Ltd.', 'sector': 'FMCG', 'cap': 'Smallcap'},
    {'symbol': 'PRAJIND', 'name': 'Praj Industries Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'RADICO', 'name': 'Radico Khaitan Ltd.', 'sector': 'FMCG', 'cap': 'Smallcap'},
    {'symbol': 'RAJRATAN', 'name': 'Rajratan Global Wire Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'RATNAMANI', 'name': 'Ratnamani Metals & Tubes Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'RAYMOND', 'name': 'Raymond Ltd.', 'sector': 'Textiles', 'cap': 'Smallcap'},
    {'symbol': 'RBLBANK', 'name': 'RBL Bank Ltd.', 'sector': 'Banking', 'cap': 'Smallcap'},
    {'symbol': 'RITES', 'name': 'RITES Ltd.', 'sector': 'Infrastructure', 'cap': 'Smallcap'},
    {'symbol': 'RPOWER', 'name': 'Reliance Power Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'RTNINDIA', 'name': 'RattanIndia Enterprises Ltd.', 'sector': 'Infrastructure', 'cap': 'Smallcap'},
    {'symbol': 'SJVN', 'name': 'SJVN Ltd.', 'sector': 'Power', 'cap': 'Smallcap'},
    {'symbol': 'SONATSOFTW', 'name': 'Sonata Software Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'STARHEALTH', 'name': 'Star Health and Allied Insurance Co Ltd.', 'sector': 'Insurance', 'cap': 'Smallcap'},
    {'symbol': 'SUVENPHAR', 'name': 'Suven Pharmaceuticals Ltd.', 'sector': 'Pharma', 'cap': 'Smallcap'},
    {'symbol': 'TANLA', 'name': 'Tanla Platforms Ltd.', 'sector': 'IT', 'cap': 'Smallcap'},
    {'symbol': 'TEJASNET', 'name': 'Tejas Networks Ltd.', 'sector': 'Telecom', 'cap': 'Smallcap'},
    {'symbol': 'TMPV', 'name': 'Tata Motors Passenger Vehicles Ltd.', 'sector': 'Auto', 'cap': 'Smallcap'},
    {'symbol': 'TRIDENT', 'name': 'Trident Ltd.', 'sector': 'Textiles', 'cap': 'Smallcap'},
    {'symbol': 'UJJIVANSFB', 'name': 'Ujjivan Small Finance Bank Ltd.', 'sector': 'Banking', 'cap': 'Smallcap'},
    {'symbol': 'UTIAMC', 'name': 'UTI Asset Management Company Ltd.', 'sector': 'Financial Services', 'cap': 'Smallcap'},
    {'symbol': 'VAIBHAVGBL', 'name': 'Vaibhav Global Ltd.', 'sector': 'Retail', 'cap': 'Smallcap'},
    {'symbol': 'VGUARD', 'name': 'V-Guard Industries Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'VIPIND', 'name': 'VIP Industries Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'VISL', 'name': 'Vedanta Iron And Steel Ltd.', 'sector': 'Metals', 'cap': 'Smallcap'},
    {'symbol': 'WELCORP', 'name': 'Welspun Corp Ltd.', 'sector': 'Capital Goods', 'cap': 'Smallcap'},
    {'symbol': 'WHIRLPOOL', 'name': 'Whirlpool of India Ltd.', 'sector': 'Consumer Durables', 'cap': 'Smallcap'},
    {'symbol': 'ZENTEC', 'name': 'Zen Technologies Ltd.', 'sector': 'Defence', 'cap': 'Smallcap'},
    {'symbol': 'TATAGOLD', 'name': 'Tata Gold ETF', 'sector': 'Commodities', 'cap': 'ETF'},
    {'symbol': 'TATASILV', 'name': 'Tata Silver ETF', 'sector': 'Commodities', 'cap': 'ETF'},
    {'symbol': 'KOTAKGOLD', 'name': 'Kotak Gold ETF', 'sector': 'Commodities', 'cap': 'ETF'},
    {'symbol': 'ICICIGOLD', 'name': 'ICICI Prudential Gold ETF', 'sector': 'Commodities', 'cap': 'ETF'},
    {'symbol': 'BSLSLVETF', 'name': 'Birla Sun Life Silver ETF', 'sector': 'Commodities', 'cap': 'ETF'},
    {'symbol': 'GROWWDEFNC', 'name': 'Groww Defence Fund', 'sector': 'Defence', 'cap': 'Mutual Fund'},
    {'symbol': 'GROWWEV', 'name': 'Groww EV & Mobility Fund', 'sector': 'Auto', 'cap': 'Mutual Fund'},
]

NIFTY_50_SYMBOLS: list[str] = [
    'RELIANCE',
    'TCS',
    'HDFCBANK',
    'ICICIBANK',
    'INFY',
    'HINDUNILVR',
    'ITC',
    'SBIN',
    'BHARTIARTL',
    'KOTAKBANK',
    'LT',
    'AXISBANK',
    'BAJFINANCE',
    'BAJAJFINSV',
    'ASIANPAINT',
    'MARUTI',
    'HCLTECH',
    'TITAN',
    'SUNPHARMA',
    'TATAMOTORS',
    'NTPC',
    'ULTRACEMCO',
    'POWERGRID',
    'WIPRO',
    'NESTLEIND',
    'TECHM',
    'JSWSTEEL',
    'TATASTEEL',
    'INDUSINDBK',
    'M&M',
    'ONGC',
    'COALINDIA',
    'ADANIENT',
    'ADANIPORTS',
    'BPCL',
    'GRASIM',
    'CIPLA',
    'DRREDDY',
    'APOLLOHOSP',
    'EICHERMOT',
    'HEROMOTOCO',
    'DIVISLAB',
    'TATACONSUM',
    'BRITANNIA',
    'BAJAJ-AUTO',
    'SBILIFE',
    'HDFCLIFE',
    'HINDALCO',
    'UPL',
    'SHRIRAMFIN',
]

def get_all_tickers() -> list[str]:
    return [s["symbol"] + ".NS" for s in NSE_UNIVERSE]

def get_by_sector(sector: str) -> list[dict]:
    return [s for s in NSE_UNIVERSE if s["sector"] == sector]
