"""NSE stock universe — Nifty 50, Next 50, and Midcap 100 constituents."""

NSE_UNIVERSE: list[dict] = [
    # ── Nifty 50 ────────────────────────────────────────────────────────
    {'symbol': 'RELIANCE', 'name': 'Reliance Industries Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'TCS', 'name': 'Tata Consultancy Services Ltd.', 'sector': 'IT'},
    {'symbol': 'HDFCBANK', 'name': 'HDFC Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'ICICIBANK', 'name': 'ICICI Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'INFY', 'name': 'Infosys Ltd.', 'sector': 'IT'},
    {'symbol': 'HINDUNILVR', 'name': 'Hindustan Unilever Ltd.', 'sector': 'FMCG'},
    {'symbol': 'ITC', 'name': 'ITC Ltd.', 'sector': 'FMCG'},
    {'symbol': 'SBIN', 'name': 'State Bank of India', 'sector': 'Banking'},
    {'symbol': 'BHARTIARTL', 'name': 'Bharti Airtel Ltd.', 'sector': 'Telecom'},
    {'symbol': 'KOTAKBANK', 'name': 'Kotak Mahindra Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'LT', 'name': 'Larsen & Toubro Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'AXISBANK', 'name': 'Axis Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'BAJFINANCE', 'name': 'Bajaj Finance Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'BAJAJFINSV', 'name': 'Bajaj Finserv Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'ASIANPAINT', 'name': 'Asian Paints Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'MARUTI', 'name': 'Maruti Suzuki India Ltd.', 'sector': 'Auto'},
    {'symbol': 'HCLTECH', 'name': 'HCL Technologies Ltd.', 'sector': 'IT'},
    {'symbol': 'TITAN', 'name': 'Titan Company Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'SUNPHARMA', 'name': 'Sun Pharmaceutical Industries Ltd.', 'sector': 'Pharma'},
    {'symbol': 'TATAMOTORS', 'name': 'Tata Motors Ltd.', 'sector': 'Auto'},
    {'symbol': 'NTPC', 'name': 'NTPC Ltd.', 'sector': 'Power'},
    {'symbol': 'ULTRACEMCO', 'name': 'UltraTech Cement Ltd.', 'sector': 'Cement'},
    {'symbol': 'POWERGRID', 'name': 'Power Grid Corporation of India Ltd.', 'sector': 'Power'},
    {'symbol': 'WIPRO', 'name': 'Wipro Ltd.', 'sector': 'IT'},
    {'symbol': 'NESTLEIND', 'name': 'Nestle India Ltd.', 'sector': 'FMCG'},
    {'symbol': 'TECHM', 'name': 'Tech Mahindra Ltd.', 'sector': 'IT'},
    {'symbol': 'JSWSTEEL', 'name': 'JSW Steel Ltd.', 'sector': 'Metals'},
    {'symbol': 'TATASTEEL', 'name': 'Tata Steel Ltd.', 'sector': 'Metals'},
    {'symbol': 'INDUSINDBK', 'name': 'IndusInd Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'M&M', 'name': 'Mahindra & Mahindra Ltd.', 'sector': 'Auto'},
    {'symbol': 'ONGC', 'name': 'Oil & Natural Gas Corporation Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'COALINDIA', 'name': 'Coal India Ltd.', 'sector': 'Metals'},
    {'symbol': 'ADANIENT', 'name': 'Adani Enterprises Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'ADANIPORTS', 'name': 'Adani Ports & Special Economic Zone Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'BPCL', 'name': 'Bharat Petroleum Corporation Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'GRASIM', 'name': 'Grasim Industries Ltd.', 'sector': 'Cement'},
    {'symbol': 'CIPLA', 'name': 'Cipla Ltd.', 'sector': 'Pharma'},
    {'symbol': 'DRREDDY', 'name': 'Dr. Reddys Laboratories Ltd.', 'sector': 'Pharma'},
    {'symbol': 'APOLLOHOSP', 'name': 'Apollo Hospitals Enterprise Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'EICHERMOT', 'name': 'Eicher Motors Ltd.', 'sector': 'Auto'},
    {'symbol': 'HEROMOTOCO', 'name': 'Hero MotoCorp Ltd.', 'sector': 'Auto'},
    {'symbol': 'DIVISLAB', 'name': 'Divis Laboratories Ltd.', 'sector': 'Pharma'},
    {'symbol': 'TATACONSUM', 'name': 'Tata Consumer Products Ltd.', 'sector': 'FMCG'},
    {'symbol': 'BRITANNIA', 'name': 'Britannia Industries Ltd.', 'sector': 'FMCG'},
    {'symbol': 'BAJAJ-AUTO', 'name': 'Bajaj Auto Ltd.', 'sector': 'Auto'},
    {'symbol': 'SBILIFE', 'name': 'SBI Life Insurance Company Ltd.', 'sector': 'Insurance'},
    {'symbol': 'HDFCLIFE', 'name': 'HDFC Life Insurance Company Ltd.', 'sector': 'Insurance'},
    {'symbol': 'HINDALCO', 'name': 'Hindalco Industries Ltd.', 'sector': 'Metals'},
    {'symbol': 'UPL', 'name': 'UPL Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'SHRIRAMFIN', 'name': 'Shriram Finance Ltd.', 'sector': 'NBFC'},

    # ── Nifty Next 50 ──────────────────────────────────────────────────
    {'symbol': 'BANKBARODA', 'name': 'Bank of Baroda', 'sector': 'Banking'},
    {'symbol': 'PNB', 'name': 'Punjab National Bank', 'sector': 'Banking'},
    {'symbol': 'CANBK', 'name': 'Canara Bank', 'sector': 'Banking'},
    {'symbol': 'IDFCFIRSTB', 'name': 'IDFC First Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'FEDERALBNK', 'name': 'Federal Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'BANDHANBNK', 'name': 'Bandhan Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'AUBANK', 'name': 'AU Small Finance Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'NAUKRI', 'name': 'Info Edge (India) Ltd.', 'sector': 'IT'},
    {'symbol': 'DMART', 'name': 'Avenue Supermarts Ltd.', 'sector': 'FMCG'},
    {'symbol': 'HAVELLS', 'name': 'Havells India Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'PIDILITIND', 'name': 'Pidilite Industries Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'GODREJCP', 'name': 'Godrej Consumer Products Ltd.', 'sector': 'FMCG'},
    {'symbol': 'DABUR', 'name': 'Dabur India Ltd.', 'sector': 'FMCG'},
    {'symbol': 'MARICO', 'name': 'Marico Ltd.', 'sector': 'FMCG'},
    {'symbol': 'COLPAL', 'name': 'Colgate-Palmolive (India) Ltd.', 'sector': 'FMCG'},
    {'symbol': 'BERGEPAINT', 'name': 'Berger Paints India Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'SIEMENS', 'name': 'Siemens Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'ABB', 'name': 'ABB India Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'BOSCHLTD', 'name': 'Bosch Ltd.', 'sector': 'Auto'},
    {'symbol': 'AMBUJACEM', 'name': 'Ambuja Cements Ltd.', 'sector': 'Cement'},
    {'symbol': 'SHREECEM', 'name': 'Shree Cement Ltd.', 'sector': 'Cement'},
    {'symbol': 'ACC', 'name': 'ACC Ltd.', 'sector': 'Cement'},
    {'symbol': 'DLF', 'name': 'DLF Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'GODREJPROP', 'name': 'Godrej Properties Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'OBEROIRLTY', 'name': 'Oberoi Realty Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'PRESTIGE', 'name': 'Prestige Estates Projects Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'MAXHEALTH', 'name': 'Max Healthcare Institute Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'FORTIS', 'name': 'Fortis Healthcare Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'LUPIN', 'name': 'Lupin Ltd.', 'sector': 'Pharma'},
    {'symbol': 'TORNTPHARM', 'name': 'Torrent Pharmaceuticals Ltd.', 'sector': 'Pharma'},
    {'symbol': 'AUROPHARMA', 'name': 'Aurobindo Pharma Ltd.', 'sector': 'Pharma'},
    {'symbol': 'ALKEM', 'name': 'Alkem Laboratories Ltd.', 'sector': 'Pharma'},
    {'symbol': 'BIOCON', 'name': 'Biocon Ltd.', 'sector': 'Pharma'},
    {'symbol': 'IPCALAB', 'name': 'IPCA Laboratories Ltd.', 'sector': 'Pharma'},
    {'symbol': 'ZYDUSLIFE', 'name': 'Zydus Lifesciences Ltd.', 'sector': 'Pharma'},
    {'symbol': 'ICICIPRULI', 'name': 'ICICI Prudential Life Insurance Co. Ltd.', 'sector': 'Insurance'},
    {'symbol': 'ICICIGI', 'name': 'ICICI Lombard General Insurance Co. Ltd.', 'sector': 'Insurance'},
    {'symbol': 'SBICARD', 'name': 'SBI Cards & Payment Services Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'MUTHOOTFIN', 'name': 'Muthoot Finance Ltd.', 'sector': 'NBFC'},
    {'symbol': 'CHOLAFIN', 'name': 'Cholamandalam Investment & Finance Co. Ltd.', 'sector': 'NBFC'},
    {'symbol': 'BAJAJHLDNG', 'name': 'Bajaj Holdings & Investment Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'M&MFIN', 'name': 'Mahindra & Mahindra Financial Services Ltd.', 'sector': 'NBFC'},
    {'symbol': 'MANAPPURAM', 'name': 'Manappuram Finance Ltd.', 'sector': 'NBFC'},
    {'symbol': 'PEL', 'name': 'Piramal Enterprises Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'RECLTD', 'name': 'REC Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'PFC', 'name': 'Power Finance Corporation Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'IRFC', 'name': 'Indian Railway Finance Corporation Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'TATAPOWER', 'name': 'Tata Power Company Ltd.', 'sector': 'Power'},
    {'symbol': 'ADANIGREEN', 'name': 'Adani Green Energy Ltd.', 'sector': 'Power'},
    {'symbol': 'ADANIPOWER', 'name': 'Adani Power Ltd.', 'sector': 'Power'},
    {'symbol': 'NHPC', 'name': 'NHPC Ltd.', 'sector': 'Power'},
    {'symbol': 'TORNTPOWER', 'name': 'Torrent Power Ltd.', 'sector': 'Power'},
    {'symbol': 'TATAELXSI', 'name': 'Tata Elxsi Ltd.', 'sector': 'IT'},
    {'symbol': 'LTIM', 'name': 'LTIMindtree Ltd.', 'sector': 'IT'},
    {'symbol': 'PERSISTENT', 'name': 'Persistent Systems Ltd.', 'sector': 'IT'},
    {'symbol': 'MPHASIS', 'name': 'Mphasis Ltd.', 'sector': 'IT'},
    {'symbol': 'COFORGE', 'name': 'Coforge Ltd.', 'sector': 'IT'},
    {'symbol': 'LTTS', 'name': 'L&T Technology Services Ltd.', 'sector': 'IT'},
    {'symbol': 'INDUSTOWER', 'name': 'Indus Towers Ltd.', 'sector': 'Telecom'},
    {'symbol': 'IOC', 'name': 'Indian Oil Corporation Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'HINDPETRO', 'name': 'Hindustan Petroleum Corporation Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'GAIL', 'name': 'GAIL (India) Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'PETRONET', 'name': 'Petronet LNG Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'IGL', 'name': 'Indraprastha Gas Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'MGL', 'name': 'Mahanagar Gas Ltd.', 'sector': 'Oil & Gas'},
    {'symbol': 'VEDL', 'name': 'Vedanta Ltd.', 'sector': 'Metals'},
    {'symbol': 'NMDC', 'name': 'NMDC Ltd.', 'sector': 'Metals'},
    {'symbol': 'SAIL', 'name': 'Steel Authority of India Ltd.', 'sector': 'Metals'},
    {'symbol': 'NATIONALUM', 'name': 'National Aluminium Company Ltd.', 'sector': 'Metals'},
    {'symbol': 'JINDALSTEL', 'name': 'Jindal Steel & Power Ltd.', 'sector': 'Metals'},
    {'symbol': 'APLAPOLLO', 'name': 'APL Apollo Tubes Ltd.', 'sector': 'Metals'},

    # ── Nifty Midcap 100 / broader picks ────────────────────────────────
    {'symbol': 'ASHOKLEY', 'name': 'Ashok Leyland Ltd.', 'sector': 'Auto'},
    {'symbol': 'TVSMOTOR', 'name': 'TVS Motor Company Ltd.', 'sector': 'Auto'},
    {'symbol': 'MRF', 'name': 'MRF Ltd.', 'sector': 'Auto'},
    {'symbol': 'MOTHERSON', 'name': 'Samvardhana Motherson International Ltd.', 'sector': 'Auto'},
    {'symbol': 'BALKRISIND', 'name': 'Balkrishna Industries Ltd.', 'sector': 'Auto'},
    {'symbol': 'EXIDEIND', 'name': 'Exide Industries Ltd.', 'sector': 'Auto'},
    {'symbol': 'BHARATFORG', 'name': 'Bharat Forge Ltd.', 'sector': 'Auto'},
    {'symbol': 'ESCORTS', 'name': 'Escorts Kubota Ltd.', 'sector': 'Auto'},
    {'symbol': 'SONACOMS', 'name': 'Sona BLW Precision Forgings Ltd.', 'sector': 'Auto'},
    {'symbol': 'TIINDIA', 'name': 'Tube Investments of India Ltd.', 'sector': 'Auto'},

    {'symbol': 'VOLTAS', 'name': 'Voltas Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'WHIRLPOOL', 'name': 'Whirlpool of India Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'CROMPTON', 'name': 'Crompton Greaves Consumer Electricals Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'BATAINDIA', 'name': 'Bata India Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'RAJESHEXPO', 'name': 'Rajesh Exports Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'PAGEIND', 'name': 'Page Industries Ltd.', 'sector': 'Textiles'},
    {'symbol': 'DIXON', 'name': 'Dixon Technologies (India) Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'BLUESTARLT', 'name': 'Blue Star Ltd.', 'sector': 'Consumer Durables'},

    {'symbol': 'PIIND', 'name': 'PI Industries Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'SRF', 'name': 'SRF Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'ATUL', 'name': 'Atul Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'DEEPAKNTR', 'name': 'Deepak Nitrite Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'NAVINFLUOR', 'name': 'Navin Fluorine International Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'CLEAN', 'name': 'Clean Science & Technology Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'AARTIIND', 'name': 'Aarti Industries Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'FLUOROCHEM', 'name': 'Gujarat Fluorochemicals Ltd.', 'sector': 'Chemicals'},

    {'symbol': 'HAL', 'name': 'Hindustan Aeronautics Ltd.', 'sector': 'Defence'},
    {'symbol': 'BEL', 'name': 'Bharat Electronics Ltd.', 'sector': 'Defence'},
    {'symbol': 'BDL', 'name': 'Bharat Dynamics Ltd.', 'sector': 'Defence'},
    {'symbol': 'COCHINSHIP', 'name': 'Cochin Shipyard Ltd.', 'sector': 'Defence'},
    {'symbol': 'SOLARINDS', 'name': 'Solar Industries India Ltd.', 'sector': 'Defence'},
    {'symbol': 'DATAPATTNS', 'name': 'Data Patterns (India) Ltd.', 'sector': 'Defence'},
    {'symbol': 'MAZAGONDOC', 'name': 'Mazagon Dock Shipbuilders Ltd.', 'sector': 'Defence'},

    {'symbol': 'CONCOR', 'name': 'Container Corporation of India Ltd.', 'sector': 'Logistics'},
    {'symbol': 'DELHIVERY', 'name': 'Delhivery Ltd.', 'sector': 'Logistics'},
    {'symbol': 'TCI', 'name': 'Transport Corporation of India Ltd.', 'sector': 'Logistics'},
    {'symbol': 'VRL', 'name': 'VRL Logistics Ltd.', 'sector': 'Logistics'},
    {'symbol': 'BLUEDART', 'name': 'Blue Dart Express Ltd.', 'sector': 'Logistics'},

    {'symbol': 'IRCTC', 'name': 'Indian Railway Catering & Tourism Corp. Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'IRB', 'name': 'IRB Infrastructure Developers Ltd.', 'sector': 'Infrastructure'},

    {'symbol': 'BHEL', 'name': 'Bharat Heavy Electricals Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'CUMMINSIND', 'name': 'Cummins India Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'THERMAX', 'name': 'Thermax Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'KAYNES', 'name': 'Kaynes Technology India Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'AIAENG', 'name': 'AIA Engineering Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'GRINFRA', 'name': 'G R Infraprojects Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'KEC', 'name': 'KEC International Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'CGPOWER', 'name': 'CG Power and Industrial Solutions Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'POLYCAB', 'name': 'Polycab India Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'HONAUT', 'name': 'Honeywell Automation India Ltd.', 'sector': 'Capital Goods'},

    {'symbol': 'TRENT', 'name': 'Trent Ltd.', 'sector': 'FMCG'},
    {'symbol': 'VBL', 'name': 'Varun Beverages Ltd.', 'sector': 'FMCG'},
    {'symbol': 'UNITDSPR', 'name': 'United Spirits Ltd.', 'sector': 'FMCG'},
    {'symbol': 'UBL', 'name': 'United Breweries Ltd.', 'sector': 'FMCG'},
    {'symbol': 'EMAMILTD', 'name': 'Emami Ltd.', 'sector': 'FMCG'},
    {'symbol': 'JYOTHYLAB', 'name': 'Jyothy Labs Ltd.', 'sector': 'FMCG'},

    {'symbol': 'ZOMATO', 'name': 'Zomato Ltd.', 'sector': 'IT'},
    {'symbol': 'PAYTM', 'name': 'One97 Communications Ltd.', 'sector': 'IT'},
    {'symbol': 'POLICYBZR', 'name': 'PB Fintech Ltd.', 'sector': 'Financial Services'},

    {'symbol': 'LICI', 'name': 'Life Insurance Corporation of India', 'sector': 'Insurance'},
    {'symbol': 'NIACL', 'name': 'New India Assurance Company Ltd.', 'sector': 'Insurance'},
    {'symbol': 'STARHEALTH', 'name': 'Star Health & Allied Insurance Co. Ltd.', 'sector': 'Insurance'},

    {'symbol': 'SUNDARMFIN', 'name': 'Sundaram Finance Ltd.', 'sector': 'NBFC'},
    {'symbol': 'LICHSGFIN', 'name': 'LIC Housing Finance Ltd.', 'sector': 'NBFC'},
    {'symbol': 'CANFINHOME', 'name': 'Can Fin Homes Ltd.', 'sector': 'NBFC'},
    {'symbol': 'POONAWALLA', 'name': 'Poonawalla Fincorp Ltd.', 'sector': 'NBFC'},

    {'symbol': 'IDEA', 'name': 'Vodafone Idea Ltd.', 'sector': 'Telecom'},
    {'symbol': 'TTML', 'name': 'Tata Teleservices (Maharashtra) Ltd.', 'sector': 'Telecom'},

    {'symbol': 'SJVN', 'name': 'SJVN Ltd.', 'sector': 'Power'},
    {'symbol': 'CESC', 'name': 'CESC Ltd.', 'sector': 'Power'},
    {'symbol': 'JSWENERGY', 'name': 'JSW Energy Ltd.', 'sector': 'Power'},

    {'symbol': 'PHOENIXLTD', 'name': 'The Phoenix Mills Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'BRIGADE', 'name': 'Brigade Enterprises Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'SOBHA', 'name': 'Sobha Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'LODHA', 'name': 'Macrotech Developers Ltd.', 'sector': 'Real Estate'},

    {'symbol': 'SYNGENE', 'name': 'Syngene International Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'LALPATHLAB', 'name': 'Dr. Lal PathLabs Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'METROPOLIS', 'name': 'Metropolis Healthcare Ltd.', 'sector': 'Healthcare'},
    {'symbol': 'MEDANTA', 'name': 'Global Health Ltd.', 'sector': 'Healthcare'},

    {'symbol': 'RAMCOCEM', 'name': 'The Ramco Cements Ltd.', 'sector': 'Cement'},
    {'symbol': 'JKCEMENT', 'name': 'JK Cement Ltd.', 'sector': 'Cement'},
    {'symbol': 'DALBHARAT', 'name': 'Dalmia Bharat Ltd.', 'sector': 'Cement'},
    {'symbol': 'BIRLASOFT', 'name': 'Birlasoft Ltd.', 'sector': 'IT'},
    {'symbol': 'INDHOTEL', 'name': 'Indian Hotels Company Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'JUBLFOOD', 'name': 'Jubilant Foodworks Ltd.', 'sector': 'FMCG'},
    {'symbol': 'PVR', 'name': 'PVR INOX Ltd.', 'sector': 'Media'},
    {'symbol': 'SUNTV', 'name': 'Sun TV Network Ltd.', 'sector': 'Media'},
    {'symbol': 'ZEEL', 'name': 'Zee Entertainment Enterprises Ltd.', 'sector': 'Media'},
    {'symbol': 'NETWORK18', 'name': 'Network18 Media & Investments Ltd.', 'sector': 'Media'},
    {'symbol': 'HATHWAY', 'name': 'Hathway Cable & Datacom Ltd.', 'sector': 'Media'},

    {'symbol': 'ABCAPITAL', 'name': 'Aditya Birla Capital Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'IIFL', 'name': 'IIFL Finance Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'ANGELONE', 'name': 'Angel One Ltd.', 'sector': 'Financial Services'},

    {'symbol': 'ASTRAL', 'name': 'Astral Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'SUPREMEIND', 'name': 'Supreme Industries Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'KEI', 'name': 'KEI Industries Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'RATNAMANI', 'name': 'Ratnamani Metals & Tubes Ltd.', 'sector': 'Metals'},

    {'symbol': 'RAYMOND', 'name': 'Raymond Ltd.', 'sector': 'Textiles'},
    {'symbol': 'ARVIND', 'name': 'Arvind Ltd.', 'sector': 'Textiles'},
    {'symbol': 'TRIDENT', 'name': 'Trident Ltd.', 'sector': 'Textiles'},
    {'symbol': 'GOKEX', 'name': 'Gokaldas Exports Ltd.', 'sector': 'Textiles'},

    {'symbol': 'KALYANKJIL', 'name': 'Kalyan Jewellers India Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'ABFRL', 'name': 'Aditya Birla Fashion & Retail Ltd.', 'sector': 'Textiles'},
    {'symbol': 'RELAXO', 'name': 'Relaxo Footwears Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'CAMPUS', 'name': 'Campus Activewear Ltd.', 'sector': 'Consumer Durables'},
    {'symbol': 'SHOPERSTOP', 'name': 'Shoppers Stop Ltd.', 'sector': 'Consumer Durables'},

    {'symbol': 'GNFC', 'name': 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'COROMANDEL', 'name': 'Coromandel International Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'SUMICHEM', 'name': 'Sumitomo Chemical India Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'CHAMBLFERT', 'name': 'Chambal Fertilisers & Chemicals Ltd.', 'sector': 'Chemicals'},

    {'symbol': 'NYKAA', 'name': 'FSN E-Commerce Ventures Ltd.', 'sector': 'FMCG'},
    {'symbol': 'HONASA', 'name': 'Honasa Consumer Ltd.', 'sector': 'FMCG'},
    {'symbol': 'SAPPHIRE', 'name': 'Sapphire Foods India Ltd.', 'sector': 'FMCG'},

    {'symbol': 'CAMS', 'name': 'Computer Age Management Services Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'CDSL', 'name': 'Central Depository Services (India) Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'BSE', 'name': 'BSE Ltd.', 'sector': 'Financial Services'},
    {'symbol': 'MCX', 'name': 'Multi Commodity Exchange of India Ltd.', 'sector': 'Financial Services'},

    {'symbol': 'JSWINFRA', 'name': 'JSW Infrastructure Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'GMRAIRPORT', 'name': 'GMR Airports Infrastructure Ltd.', 'sector': 'Infrastructure'},
    {'symbol': 'NLCINDIA', 'name': 'NLC India Ltd.', 'sector': 'Power'},
    {'symbol': 'TATACOMM', 'name': 'Tata Communications Ltd.', 'sector': 'Telecom'},
    {'symbol': 'CENTRALBK', 'name': 'Central Bank of India', 'sector': 'Banking'},
    {'symbol': 'INDIANB', 'name': 'Indian Bank', 'sector': 'Banking'},
    {'symbol': 'IOB', 'name': 'Indian Overseas Bank', 'sector': 'Banking'},
    {'symbol': 'IDBI', 'name': 'IDBI Bank Ltd.', 'sector': 'Banking'},
    {'symbol': 'RBLBANK', 'name': 'RBL Bank Ltd.', 'sector': 'Banking'},

    {'symbol': 'GLENMARK', 'name': 'Glenmark Pharmaceuticals Ltd.', 'sector': 'Pharma'},
    {'symbol': 'NATCOPHARM', 'name': 'Natco Pharma Ltd.', 'sector': 'Pharma'},
    {'symbol': 'LAURUSLABS', 'name': 'Laurus Labs Ltd.', 'sector': 'Pharma'},
    {'symbol': 'GRANULES', 'name': 'Granules India Ltd.', 'sector': 'Pharma'},
    {'symbol': 'AJANTPHARM', 'name': 'Ajanta Pharma Ltd.', 'sector': 'Pharma'},

    {'symbol': 'HSCL', 'name': 'Himadri Speciality Chemical Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'FINEORG', 'name': 'Fine Organic Industries Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'TATACHEM', 'name': 'Tata Chemicals Ltd.', 'sector': 'Chemicals'},

    {'symbol': 'SUNTECK', 'name': 'Sunteck Realty Ltd.', 'sector': 'Real Estate'},
    {'symbol': 'MAHLIFE', 'name': 'Mahindra Lifespace Developers Ltd.', 'sector': 'Real Estate'},

    {'symbol': 'FACT', 'name': 'Fertilisers And Chemicals Travancore Ltd.', 'sector': 'Chemicals'},
    {'symbol': 'DEEPAKFERT', 'name': 'Deepak Fertilisers & Petrochemicals Ltd.', 'sector': 'Chemicals'},

    {'symbol': 'OFSS', 'name': 'Oracle Financial Services Software Ltd.', 'sector': 'IT'},
    {'symbol': 'CYIENT', 'name': 'Cyient Ltd.', 'sector': 'IT'},
    {'symbol': 'ZENSAR', 'name': 'Zensar Technologies Ltd.', 'sector': 'IT'},
    {'symbol': 'HAPPSTMNDS', 'name': 'Happiest Minds Technologies Ltd.', 'sector': 'IT'},
    {'symbol': 'ROUTE', 'name': 'Route Mobile Ltd.', 'sector': 'IT'},

    {'symbol': 'LAXMIMACH', 'name': 'Lakshmi Machine Works Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'ELGIEQUIP', 'name': 'Elgi Equipments Ltd.', 'sector': 'Capital Goods'},
    {'symbol': 'ISGEC', 'name': 'ISGEC Heavy Engineering Ltd.', 'sector': 'Capital Goods'},
]

# ── Nifty 50 symbol list ───────────────────────────────────────────────
NIFTY_50_SYMBOLS: list[str] = [
    'RELIANCE', 'TCS', 'HDFCBANK', 'ICICIBANK', 'INFY',
    'HINDUNILVR', 'ITC', 'SBIN', 'BHARTIARTL', 'KOTAKBANK',
    'LT', 'AXISBANK', 'BAJFINANCE', 'BAJAJFINSV', 'ASIANPAINT',
    'MARUTI', 'HCLTECH', 'TITAN', 'SUNPHARMA', 'TATAMOTORS',
    'NTPC', 'ULTRACEMCO', 'POWERGRID', 'WIPRO', 'NESTLEIND',
    'TECHM', 'JSWSTEEL', 'TATASTEEL', 'INDUSINDBK', 'M&M',
    'ONGC', 'COALINDIA', 'ADANIENT', 'ADANIPORTS', 'BPCL',
    'GRASIM', 'CIPLA', 'DRREDDY', 'APOLLOHOSP', 'EICHERMOT',
    'HEROMOTOCO', 'DIVISLAB', 'TATACONSUM', 'BRITANNIA', 'BAJAJ-AUTO',
    'SBILIFE', 'HDFCLIFE', 'HINDALCO', 'UPL', 'SHRIRAMFIN',
]


def get_all_tickers() -> list[str]:
    """Return every symbol in `SYMBOL.NS` format for yfinance."""
    return [s['symbol'] + '.NS' for s in NSE_UNIVERSE]


def get_by_sector(sector: str) -> list[dict]:
    """Return stocks belonging to *sector* (case-insensitive match)."""
    sector_lower = sector.lower()
    return [s for s in NSE_UNIVERSE if s['sector'].lower() == sector_lower]
